[build]
  publish = "dist"
  command = "ng build --configuration production"

[build.environment]
  NODE_VERSION = "20"

# SPA redirect for Angular Router (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Form handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle demo routes
[[redirects]]
  from = "/demos/bella-vista-restaurant/"
  to = "/bella-vista.html"
  status = 200

[[redirects]]
  from = "/templates/local-business/"
  to = "/local-business.html"
  status = 200

[[redirects]]
  from = "/client-proposals/refined-cravings/"
  to = "/refined-cravings.html"
  status = 200

[[redirects]]
  from = "/client-proposals/cafe-cultivate/"
  to = "/cafe-cultivate.html"
  status = 200