[build]
  publish = "."
  command = ""

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# SPA routing - handle product pages and other routes
[[redirects]]
  from = "/products/*"
  to = "/products/:splat"
  status = 200

# Handle 404s - redirect to home page for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Form handling is automatic with Netlify Forms
# No additional configuration needed for forms with netlify attribute